### PR TITLE
Compact icon set for Tree

### PR DESCRIPTION
**Pull request by fedosov**
I propose to use a more compact set ([famfamfam.com](http://www.famfamfam.com)) of icons for a Tree. Please see the attached image.

umongo-20130429

### CODE REVIEW

**Comment by leesei** [comment]
+1

**Comment by fedosov** [comment]
Bump!

**Comment by agirbal** [comment]
this looks good, will put it in 1.6.0.
Ideally want to make icons better / more consistent across the board.

**Comment by agirbal** [comment]
I've merged the new icons, thanks!

**Pull request closed without merging**
